export const PATH = {
  HOME: '/',
  PROFILE: '/profile',
  COLLECTION: '/collection',
  NOTI: '/noti',
  SEARCH: '/search',
  LOGIN: '/login',
  REGISTER: '/register',
  NEW_FEED: '/new/feed',
  EDIT_FEED: '/edit/feed',
  DETAIL_FEED: '/detail/feed',
  SETTING: '/setting',
  SETTING_NOTI: '/setting/noti',
  SETTING_PROFILE: '/setting/profile',
  SETTING_ACCOUNT: '/setting/account',
  PASSWORD: '/password',
  ACCOUNT: '/account',
  FOLLOWER: '/followers',
  FOLLOWING: '/followings',
  STORE: '/store',
};
