export const PATH = {
  HOME: '/',
  PROFILE: '/profile',
  PROFILE_EDIT: '/profile/edit',
  COLLECTION: '/collection',
  NOTI: '/noti',
  SEARCH: '/search',
  LOGIN: '/login',
  REGISTER: '/register',
  NEW_FEED: '/new/feed',
  EDIT_FEED: '/edit/feed',
  DETAIL_FEED: '/detail/feed',
  SETTING: '/setting',
  SETTING_NOTI: '/setting/noti',
  PASSWORD: '/password',
  ACCOUNT: '/account',
};
