= FoodyMoody Application API Document
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:

[[feed]]
== 피드

=== 피드 등록
operation::registerFeed[snippets='http-request,http-response']

[[auth]]
== 보안

=== 로그인

operation::login_success[snippets='http-request,http-response']

=== 로그아웃

operation::logout_success[snippets='http-request,http-response']

[[comment]]
== 댓글

=== 댓글 등록

==== 성공

operation::registerComment_success[snippets='http-request,http-response']

==== 바디가 없을 때

operation::registerComment_failed_by_request_body_not_exists[snippets='http-request,http-response']

==== 댓글이 없을 때

operation::registerComment_failed_by_content_not_exists[snippets='http-request,http-response']

==== 댓글이 비여 있으면

operation::registerComment_failed_by_content_is_empty[snippets='http-request,http-response']

==== 댓글이 공백 일때

operation::registerComment_failed_by_content_is_blank[snippets='http-request,http-response']

==== 댓글이 200자를 넘을 때

operation::registerComment_failed_by_content_is_larger_than_200[snippets='http-request,http-response']

==== 피드가 존재하지 않을 때

operation::registerComment_failed_by_feed_not_exists[snippets='http-request,http-response']

==== 피드 아이디가 없을 때

operation::registerComment_failed_by_feed_id_not_exists[snippets='http-request,http-response']

