= FoodyMoody Application API Document
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 3
:sectlinks:

[[feed]]
== 피드

=== 피드 등록

operation::registerFeed[snippets='http-request,http-response']

=== 피드 전체 조회

operation::readAllFeed[snippets='http-request,http-response']

=== 피드 개별 조회

operation::readFeed[snippets='http-request,http-response']

=== 피드 수정

operation::updateFeed[snippets='http-request']

=== 피드 삭제

operation::deleteFeed[snippets='http-request']

=== 스토어 무드 조회

operation::readAllStoreMood[snippets='http-request,http-response']

[[colletion]]
== 컬렉션

=== 컬렉션 등록

operation::feed-collection-create-success[snippets='http-request,http-response']

[[like]]
== 좋아요

=== 좋아요 등록

==== 성공

operation::like[snippets='http-request,http-response']

==== 이미 좋아요 된 피드일 때

operation::likeFailed[snippets='http-request,http-response']

=== 좋아요 취소

==== 성공

operation::unLike[snippets='http-request,http-response']

==== 좋아요 된 피드가 없을 때

operation::unLikeFailed[snippets='http-request,http-response']

[[auth]]
== 인증/인가

=== 로그인

==== 성공

operation::login_success[snippets='http-request,http-response']

==== 가입되지 않은 이메일일 때

operation::login_failedByUnregisteredEmail[snippets='http-response']

==== 비밀번호가 틀렸을 때

operation::login_failedByWrongPassword[snippets='http-response']

[[comment]]
== 댓글

=== 댓글 등록

==== 성공

operation::comment_register_success[snippets='http-request,http-response']

==== 바디가 없을 때

operation::comment_register_failed_by_request_body_not_exists[snippets='http-response']

==== 댓글이 없을 때

operation::comment_register_failed_by_content_not_exists[snippets='http-response']

==== 댓글이 비여 있으면

operation::comment_register_failed_by_content_is_empty[snippets='http-response']

==== 댓글이 공백 일때

operation::comment_register_failed_by_content_is_blank[snippets='http-response']

==== 댓글이 200자를 넘을 때

operation::comment_register_failed_by_content_is_larger_than_200[snippets='http-response']

==== 피드가 존재하지 않을 때

operation::comment_register_failed_by_feed_not_exists[snippets='http-response']

==== 피드 아이디가 없을 때

operation::comment_register_failed_by_feed_id_not_exists[snippets='http-response']

=== 댓글 수정

==== 성공

operation::comment_edit_success[snippets='http-request,http-response']

==== 바디가 없을 때

operation::comment_edit_failed_by_request_body_not_exists[snippets='http-response']

==== 댓글이 비여 있으면

operation::editComment_failed_by_content_is_empty[snippets='http-response']

==== 댓글이 공백 일때

operation::comment_edit_failed_by_content_is_blank[snippets='http-response']

==== 댓글이 200자를 넘을 때

operation::comment_edit_failed_by_content_is_larger_than_200[snippets='http-response']

==== 댓글이 존재하지 않을 때

operation::comment_edit_failed_by_comment_not_exists[snippets='http-response']

==== 댓글이 이미 삭제되었을 때

operation::comment_edit_failed_by_comment_is_deleted[snippets='http-response']

=== 댓글 삭제

==== 성공

operation::comment_delete_success[snippets='http-request,http-response']

==== 댓글이 존재하지 않을 때

operation::comment_delete_failed_by_comment_not_exists[snippets='http-response']

==== 댓글이 이미 삭제되었을 때

operation::comment_delete_failed_by_comment_is_deleted[snippets='http-response']

=== 피드별 댓글 조회

==== 성공

operation::comments_fetch_success[snippets='http-request,http-response']

==== 성공 - 로그인

operation::comments_fetch_with_with_access_token_success[snippets='http-request,http-response']

==== 성공 - 로그인(좋아요)

operation::comments_fetch_with_with_access_token_success[snippets='http-request,http-response']

==== 성공 - 페이징

operation::comments_fetch_with_page_success[snippets='http-request,http-response']

==== 피드가 존재하지 않을 때

operation::comments_fetch_failed_by_feed_id_not_exists[snippets='http-response']

=== 댓글 하트

==== 댓글 하트 등록

operation::comment_heart_register_success[snippets='http-request,http-response']

==== 댓글 하트 취소

operation::comment_heart_cancel_success[snippets='http-request,http-response']

[[reply]]
== 대댓글

=== 대댓글 달기

operation::comment_reply_success[snippets='http-request,http-response']

=== 대댓글 조회

operation::comment_reply_fetch_success[snippets='http-request,http-response']

[[member]]
== 회원

=== 회원 가입

==== 성공

operation::signupMember_success[snippets='http-request,http-response']

==== 입력값이 잘못됐을 때

operation::signupMember_failedByMultipleInvalidInput[snippets='http-response']

==== 이미 가입된 이메일일 때

operation::signupMember_failedByDuplicateEmail[snippets='http-response']

==== 이미 가입된 닉네임일 때

operation::signupMember_failedByDuplicateNickname[snippets='http-response']

==== 재입력한 패스워드가 다를 때

operation::signupMember_failedByReconfirmPasswordUnmatch[snippets='http-response']

=== 회원 프로필 조회

==== 성공

operation::fetchMemberProfile_success[snippets='http-request,http-response']

==== 존재하지 않는 회원 id일 때

operation::fetchMemberProfile_failedByIdNotFound[snippets='http-response']

=== 회원별 피드 조회

==== 성공

operation::fetchMemberFeeds_success[snippets='http-request,http-response']

==== 성공 - 해당 회원이 작성한 피드가 없을 때

operation::fetchMemberFeedsEmpty_success[snippets='http-response']

=== 테이스트 무드 조회

==== 성공

operation::fetchAllTasteMoods_success[snippets='http-request,http-response']

[[notification]]
== 알람

=== 알람 전체 조회

==== 성공 - 페이징

operation::notification_request_all_success[snippets='http-request,http-response']

=== 개별 알람 조회

==== 성공 (예시: 읽음으로 변경 )

operation::notification_request_single_success[snippets='http-request,http-response']

=== 알람 개별 상태 변경

==== 성공 - 읽음

operation::notification_change_status_success[snippets='http-request,http-response']

=== 알람 일괄 상태 변경

==== 성공 - 읽음

operation::notification_change_all_status_success[snippets='http-request,http-response']

=== 알람 개별 삭제

==== 성공

operation::notification_delete_success[snippets='http-request,http-response']

=== 알람 전체 삭제

==== 성공

operation::notification_delete_all_success[snippets='http-request,http-response']

=== 알람 일괄적으로 삭제

==== 성공

operation::notification_delete_notification_list_success[snippets='http-request,http-response']

== 알람 설정

=== 알람 설정 조회

==== 성공

operation::notification_setting_request_success[snippets='http-request,http-response']

=== 알람 설정 변경

==== 성공

operation::notification_setting_update_success[snippets='http-request,http-response']

== SSE

=== 알람 실시간 전송

operation::sse_request_success[snippets='http-request,http-response']

[[image]]
== 이미지

=== 이미지 업로드 공통

요청 body에 이미지 파일이 깨져서 나와서 curl입니다

==== 이미지 크기가 2.8MB보다 클 때

operation::uploadFeedImageOverSizeLimit_Fail[snippets='http-response']

==== 지원되지 않는 형식의 이미지일 때

현재 jpeg(jpg), png 지원됩니다

operation::uploadFeedImageWithUnsupportedFormat_Fail[snippets='http-response']

=== 회원 이미지 업로드

==== 성공

operation::uploadMemberProfileImage_success[snippets='curl-request,http-response']

=== 피드 이미지 업로드

==== 성공

operation::uploadFeedImage_success[snippets='curl-request,http-response']

==== 존재하지 않는 피드 아이디일 때

operation::uploadFeedImage_failedByFeedNotFound[snippets='http-response']

==== 현재 로그인한 회원이 피드 작성자가 아닐 때

operation::uploadFeedImage_failedByUnauthorized[snippets='http-response']

=== 이미지 삭제

==== 성공

operation::deleteFeedImage_success[snippets='http-request,http-response']

==== 존재하지 않는 이미지 id일 때

operation::deleteFeedImage_failedByNotExistId[snippets='http-response']

==== 현재 로그인한 회원이 업로드한 이미지가 아닐 때

operation::deleteFeedImage_failedByUnAuthorized[snippets='http-response']

