export const QUERY_KEY = {
  profile: 'profile',
  nickname: 'nickname',
  allFeeds: 'allFeeds',
  feedDetail: 'feedDetail',
  comments: 'comments',
  replies: 'replies',
  tasteMood: 'tasteMood',
  storeMood: 'storeMood',
  notifications: 'notifications',
  followings: 'followings',
  followers: 'followers',
  collections: 'collections',
  refresh: 'refresh',
};
