export const QUERY_KEY = {
  profile: 'profile',
  nickname: 'nickname',
  profileFeeds: 'profileFeeds',
  profileCollections: 'profileCollections',
  allFeeds: 'allFeeds',
  feedDetail: 'feedDetail',
  comments: 'comments',
  replies: 'replies',
  tasteMood: 'tasteMood',
  storeMood: 'storeMood',
  stores: 'stores',
  notifications: 'notifications',
  followings: 'followings',
  followers: 'followers',
  collections: 'collections',
  myCollections: 'myCollections',
  myCollectionsContainFeed: 'myCollectionsContainFeed',
  collectionDetail: 'collectionDetail',
  notificationSetting: 'notificationSettings',
  refresh: 'refresh',
};
