name: be-cd
on:
  push:
    branches:
      - release

env:
  ROOT_PATH: "./be"

jobs:
  be-cd:
    runs-on: ubuntu-latest
    steps:
      - name: 레포지토리를 체크아웃한다
        uses: actions/checkout@v4
      - name: 자바를 설치한다
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '11'
      - name: 어플리케이션을 빌드한다
        run: |
          chmod +x gradlew
          ./gradlew build
        working-directory: ${{ env.ROOT_PATH }}
      - name: 도커 허브에 로그인한다
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: 어플리케이션의 도커 이미지를 빌드하고 도커 허브에 푸시한다
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.be
          push: true
          tags: ${{ secrets.BE_DOCKER_IMAGE_NAME }}
      - name: 어플리케이션을 배포한다
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_ADDRESS }}
          username: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.HOST_KEY }}
          port: ${{ secrets.HOST_PORT }}
          script: |
            sudo docker compose -f docker-compose-be-app.yml down -v
            sudo docker compose -f docker-compose-be-app.yml pull
            sudo docker compose -f docker-compose-be-app.yml up -d
            sudo docker image prune -f
