name: be-ci
on:
  pull_request:
    branches:
      - dev-be
env:
  BUILD_FILE_PATH: "./be/gradlew"

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: 레포지토리를 체크아웃한다
        uses: actions/checkout@v4
      - name: 자바를 설치한다
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '11'
      - name: 실행권한을 부여한다
        run: chmod +x ${{ env.BUILD_FILE_PATH }}
      - name: 빌드한다
        run: |
          cd be
          ./gradlew build 

  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: 레포지토리를 체크아웃한다
        uses: actions/checkout@v4
      - name: 자바를 설치한다
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '11'
      - name: 실행권한을 부여한다
        run: chmod +x ${{ env.BUILD_FILE_PATH }}
      - name: 테스트를 실행한다
        run: |
          cd be
          ./gradlew test
      - name: CoverAlls를 실행한다
        uses: coverallsapp/github-action@v2
        with:
          base-path: ./be/build/reports/jacoco/test/jacocoTestReport.xml
